# Generated by Django 2.2.6 on 2020-04-19 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0002_skintype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skintype',
            name='dry',
            field=models.IntegerField(choices=[(2, '적다'), (5, '매우 많다'), (4, '많다'), (1, '매우적다'), (3, '보통이다')]),
        ),
        migrations.AlterField(
            model_name='skintype',
            name='oily',
            field=models.IntegerField(choices=[(2, '적다'), (5, '매우 많다'), (4, '많다'), (1, '매우적다'), (3, '보통이다')]),
        ),
        migrations.AlterField(
            model_name='skintype',
            name='sensitive',
            field=models.IntegerField(choices=[(2, '적다'), (5, '매우 많다'), (4, '많다'), (1, '매우적다'), (3, '보통이다')]),
        ),
    ]
